export { ProfileBox } from "./profileBox";
export { MapBox } from "./mapBox";
export { ThemeToggleBox } from "./themeToggleBox";
export { ResumeBox } from "./resumeBox";
export { BannerBox } from "./bannerBox";
export { LinkedinBox } from "./linkedinBox";
export { GithubBox } from "./githubBox";
export { MailBox } from "./mailBox";
export { MaltBox } from "./maltBox";
export { SkillsBox } from "./skillsBox";
export { ExperienceBox } from "./experienceBox";

export { LbfBox } from "./project/lbfBox";
export { UnityBox } from "./project/unityBox";
export { WebpizzaBox } from "./project/webpizzaBox";
export { WaveChatBox } from "./project/waveChatBox";
export { PeppersoftBox } from "./project/peppersoftBox";
export { EuresisBox } from "./project/euresisBox";
export { RePairBox } from "./project/rePairBox";
